# Error & Exceptions

## Handling errors

```sh
# You should check the http response status code.
```

```javascript
// Promises should be used to check for any error
// and/or success of the request.
// Let's assume invoice has already been instantiated

invoice.save().then(
    function(invoice) {
        // Here, the request was successful, and invoice
        // has been filled with the response's data. You
        // may continue your work here, safe.

    }, function(err) {
        // An error occured during the request. You may
        // check the error message in err.
        console.log(err);

    });
```

```php
<?php
// Different type of exceptions may be thrown by the
// ProcessOut's PHP library, depending on the situation.
// Let's assume $invoice has already been instantiated

try
{
    $invoice->save();
}
catch(ProcessOut\Exceptions\APIAuthenticationException $e)
{
    // It seems your API credentials are wrong
    echo $e->getMessage();
}
catch(ProcessOut\Exceptions\ApiException $e)
{
    // There's been an error with your request
    echo $e->getMessage();
}
catch(ProcessOut\Exceptions\NotFoundException $e)
{
    // The ressource you were trying to access
    // could not be found
    echo $e->getMessage();
}
?>
```

```csharp
// Different type of exceptions may be thrown by the
// ProcessOut's C# library, depending on the situation.
// Let's assume Invoice has already been instantiated

try
{
    Invoice.Save();
}
catch (ProcessOut.Exceptions.ApiAuthenticationException e)
{
    // It seems your API credentials are wrong
    Console.WriteLine(e.Message);
}
catch (ProcessOut.Exceptions.ApiException e)
{
    // There's been an error with your request
    Console.WriteLine(e.Message);
}
catch (ProcessOut.Exceptions.NotFoundException e)
{
    // The ressource you were trying to access
    // could not be found
    Console.WriteLine(e.Message);
}
```

```python
from processout.exceptions.apiauthenticationexception import ApiAuthenticationException
from processout.exceptions.apiexception               import ApiException
from processout.exceptions.notfoundexception          import NotFoundException

# Different type of exceptions may be thrown by the
# ProcessOut's Python library, depending on the situation.
# Let's assume invoice has already been instantiated

try:
    invoice.save()

except ApiAuthenticationException as e:
    print('Looks like your project id or secret is wrong. ' + str(e))

except ApiException as e:
    print('Looks like theres been an API error. ' + str(e))

except NotFoundException as e:
    print('Looks like the ressource you were trying to fetch could not be found' + str(e))
```

ProcessOut provides easy ways of handling errors through its libraries.
